ps2exe `
-inputFile ..\src\countingsheeps.ps1 `
-iconFile ..\assets\bluesheep.ico `
-noConsole `
-noOutput `
-exitOnCancel `
-title "CountingSheeps" `
-description "Count words quick !" `
-company "Skrivanek GmbH" `
-copyright "CC0 1.0 Universal Stella - stella.menier@gmx.de" `
-version 0.9 `
-Verbose `
-outputFile ..\releases\countingsheeps.exe
